# Generated by Django 4.2.2 on 2023-06-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UUID',
            new_name='UID',
        ),
    ]
