# Generated by Django 4.2.2 on 2023-06-27 03:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('money', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('icon', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('friend', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='friends.friend')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
