# Generated by Django 4.2.2 on 2023-06-27 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sum', models.IntegerField(default=0)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('thumbnail', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('avatar', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('last_log', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_log'],
            },
        ),
    ]
